steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/prototype:latest', '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/prototype:latest']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'prototype'
  - '--image'
  - 'gcr.io/$PROJECT_ID/prototype:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '1'
  - '--timeout'
  - '300'
  - '--max-instances'
  - '10'
  - '--min-instances'
  - '0'
  - '--set-env-vars'
  - 'FLASK_ENV=production,FLASK_DEBUG=false'
  - '--port'
  - '5000'

images:
- gcr.io/$PROJECT_ID/prototype:latest