# Cloud Run Service Configuration
# Use this with: gcloud run services replace cloudrun-service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: truthguard-app
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and memory allocation (optimized for quota limits)
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "1Gi"
        # Max instances to prevent runaway costs and stay within quota
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "0"
        # Extended timeout for ML processing and container startup
        run.googleapis.com/timeout: "900s"
        # Startup probe configuration
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/truthguard-app:latest
        ports:
        - name: http1
          containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_DEBUG
          value: "false"
        # Add your API keys here as environment variables
        # - name: VIRUSTOTAL_API_KEY
        #   value: "your_api_key_here"
        # - name: GOOGLE_GENERATIVE_AI_KEY
        #   value: "your_api_key_here"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true